# RTL of CPU_CORE and everything below it (mmRISC-2 submodule, read unmodified),
# relative to the repository root. The caches are outside CPU_CORE.
mmRISC-2/RTL/CPU/CPU_CORE/CORE_BTB/CORE_BTB.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_IFU/CORE_IFU.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_DECOMP/CORE_DECOMP.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_DEC/CORE_DEC.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_RF/CORE_RF.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_FRF/CORE_FRF.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_EXU/CORE_EXU.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_MDU/CORE_MDU.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_CSR/CORE_CSR.sv
mmRISC-2/RTL/CPU/CPU_CORE/CORE_LSU/CORE_LSU.sv
mmRISC-2/RTL/CPU/CPU_CORE/CPU_CORE/CPU_CORE.sv
mmRISC-2/RTL/CPU/CPU_FPU/FPU_ROUND/FPU_ROUND.sv
mmRISC-2/RTL/CPU/CPU_FPU/CORE_FPU/CORE_FPU.sv
mmRISC-2/RTL/CPU/CPU_MMU/MMU_TLB/MMU_TLB.sv
mmRISC-2/RTL/CPU/CPU_MMU/MMU_PMP/MMU_PMP.sv
mmRISC-2/RTL/CPU/CPU_MMU/MMU_PTW/MMU_PTW.sv
mmRISC-2/RTL/CPU/CPU_MMU/CORE_MMU/CORE_MMU.sv
